sudo: required

services:
  - docker

script:
  - docker build -t beevelop/ionic .
  - docker run beevelop/ionic /bin/sh -c "ionic -v && ionic start test blank --no-link --no-git --cordova && cd test && ionic cordova platform add android && ionic cordova build android"
  
  
